#!/bin/bash
# This script copies zine into PREFIX and compiles the python
# files with PYTHON.  If PREFIX is not defined /usr is assumed.

SRC="`dirname $0`/../zine"
PACKAGES="_dynamic _ext importers utils views websetup i18n docs"
SCRIPTS="create-apache-config server shell"


if [ x$PREFIX == x ]; then
  PREFIX=/usr
fi
if [ x$PYTHON == x ]; then
  PYTHON=`which python`
fi

echo "Installing to $PREFIX"
echo "Using $PYTHON"

# make sure the target folders exist
mkdir -p $PREFIX/lib/zine/zine
mkdir -p $PREFIX/share/zine

# the packages to copy
cp $SRC/*.py $PREFIX/lib/zine/zine
for package in $PACKAGES; do
  mkdir -p $PREFIX/lib/zine/zine/$package
  cp -R $SRC/$package $PREFIX/lib/zine/zine/
done

# all the plugins
cp -R $SRC/plugins $PREFIX/lib/zine

# compile all files
$PYTHON -O -mcompileall -qf $PREFIX/lib/zine/{zine,plugins}

# templates and shared data
cp -R $SRC/shared $PREFIX/share/zine/htdocs
cp -R $SRC/templates $PREFIX/share/zine/templates

# copy the server files and adjust the ZINE_LIB path
cp -R $SRC/../servers $PREFIX/share/zine
sed -i '' -E -e "s|^ZINE_LIB =.*$|ZINE_LIB = '$PREFIX/lib/zine'|g" \
    -e "s|^#!/usr/bin/python|#!$PYTHON|g" $PREFIX/share/zine/servers/*

# copy some of the scripts
mkdir -p $PREFIX/share/zine/scripts
for script in $SCRIPTS; do
  cp $SRC/../scripts/$script $PREFIX/share/zine/scripts
  chmod +x $PREFIX/share/zine/scripts
done
cp $SRC/../scripts/_init_zine.py $PREFIX/share/zine/scripts
sed -i '' -E -e "s|^ZINE_LIB = None$|ZINE_LIB = '$PREFIX/lib/zine'|g" \
   $PREFIX/share/zine/scripts/_init_zine.py
sed -i '' -E -e "s|^#!/usr/bin/(env )?python|#!$PYTHON|g" \
   $PREFIX/share/zine/scripts/*

echo "All done."
