#!/bin/bash
# This script copies textpress into PREFIX and compiles the python
# files with PYTHON.  If PREFIX is not defined /usr is assumed.

SRC="`dirname $0`/../textpress"
PACKAGES="_dynamic _ext importers parsers utils views websetup i18n"

if [ x$PREFIX == x ]; then
  PREFIX=/usr
fi
if [ x$PYTHON == x ]; then
  PYTHON=`which python`
fi

echo "Installing to $PREFIX"
echo "Using $PYTHON"

# make sure the target folders exist
mkdir -p $PREFIX/lib/textpress/textpress
mkdir -p $PREFIX/share/textpress

# the packages to copy
cp $SRC/*.py $PREFIX/lib/textpress/textpress
for package in $PACKAGES; do
  mkdir -p $PREFIX/lib/textpress/textpress/$package
  cp -R $SRC/$package $PREFIX/lib/textpress/textpress/
done

# all the plugins
cp -R $SRC/{experimental_,}plugins $PREFIX/lib/textpress

# compile all files
$PYTHON -O -mcompileall -qf $PREFIX/lib/textpress/{textpress,plugins}

# templates and shared data
cp -R $SRC/shared $PREFIX/share/textpress/htdocs
cp -R $SRC/templates $PREFIX/share/textpress/templates

# copy the server files and adjust the TEXTPRESS_LIB path
cp -R $SRC/../servers $PREFIX/share/textpress
sed -i'' -r "s|^TEXTPRESS_LIB\s*=.*$|TEXTPRESS_LIB = '$PREFIX/lib/textpress'|g" $PREFIX/share/textpress/servers/*


echo "All done."
