#!/bin/bash
# This script copies zine into PREFIX and compiles the python
# files with PYTHON.  If PREFIX is not defined /usr is assumed.

SRC="`dirname $0`/../zine"
PACKAGES="_dynamic _ext importers parsers utils views websetup i18n"

if [ x$PREFIX == x ]; then
  PREFIX=/usr
fi
if [ x$PYTHON == x ]; then
  PYTHON=`which python`
fi

echo "Installing to $PREFIX"
echo "Using $PYTHON"

# make sure the target folders exist
mkdir -p $PREFIX/lib/zine/zine
mkdir -p $PREFIX/share/zine

# the packages to copy
cp $SRC/*.py $PREFIX/lib/zine/zine
for package in $PACKAGES; do
  mkdir -p $PREFIX/lib/zine/zine/$package
  cp -R $SRC/$package $PREFIX/lib/zine/zine/
done

# all the plugins
cp -R $SRC/{experimental_,}plugins $PREFIX/lib/zine

# compile all files
$PYTHON -O -mcompileall -qf $PREFIX/lib/zine/{zine,plugins}

# templates and shared data
cp -R $SRC/shared $PREFIX/share/zine/htdocs
cp -R $SRC/templates $PREFIX/share/zine/templates

# copy the server files and adjust the ZINE_LIB path
cp -R $SRC/../servers $PREFIX/share/zine
sed -i'' -r "s|^ZINE_LIB\s*=.*$|ZINE_LIB = '$PREFIX/lib/zine'|g" $PREFIX/share/zine/servers/*


echo "All done."
