#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Manage Database
    ~~~~~~~~~~~~~~~

    Database maintenance script.

    :copyright: (c) 2009 by the Zine Team, see AUTHORS for more details.
    :license: BSD, see LICENSE for more details.
"""

import sys
from os.path import dirname
sys.path.append(dirname(__file__))
from _init_zine import find_instance
from zine.upgrades import CommandLineInterface

def main():
    manage = CommandLineInterface()
    manage.run()

if __name__ == '__main__':
    main()
