#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Open a TextPress Server
    ~~~~~~~~~~~~~~~~~~~~~~

    This script opens a development server for TextPress.

    :copyright: 2008 by Armin Ronacher.
    :license: GNU GPL.
"""
import sys
from os.path import abspath, join, pardir, isfile, dirname
from optparse import OptionParser
from werkzeug import run_simple


sys.path.append(dirname(__file__))
from _init_textpress import find_instance
from textpress import make_app


def main():
    parser = OptionParser(usage='%prog [options] [instance]')
    parser.add_option('--hostname', '-a', dest='hostname', default='localhost')
    parser.add_option('--port', '-p', dest='port', type='int', default=4000)
    parser.add_option('--no-reloader', dest='reloader', action='store_false',
                      default=True, help='Disable the reloader')
    parser.add_option('--no-debugger', dest='debugger', action='store_false',
                      default=True, help='Disable the debugger')
    parser.add_option('--profile', dest='profile', action='store_true',
                      help='Enable the profiler')
    options, args = parser.parse_args()
    if not args:
        instance = find_instance()
        if instance is None:
            parser.error('instance not found.  Specify path to instance')
    elif len(args) == 1:
        instance = args[0]
    else:
        parser.error('incorrect number of arguments')
    
    app = make_app(instance)
    if options.profile:
        from werkzeug.contrib.profiler import ProfilerMiddleware
        app = ProfilerMiddleware(app, stream=sys.stderr)

    run_simple(options.hostname, options.port, app,
               use_reloader=options.reloader, use_debugger=options.debugger)


if __name__ == '__main__':
    main()
