#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Open a TextPress Shell
    ~~~~~~~~~~~~~~~~~~~~~~

    This script opens a shell for TextPress.

    :copyright: 2008 by Armin Ronacher.
    :license: GNU GPL.
"""
import sys
from os.path import abspath, join, pardir, isfile, dirname
from optparse import OptionParser
from werkzeug.script import make_shell


sys.path.append(dirname(__file__))
from _init_textpress import find_instance


def init_func(instance):
    from textpress import make_textpress
    app = make_textpress(instance, True)
    from textpress import models
    from textpress.database import db
    del make_textpress
    return locals()


def main():
    parser = OptionParser(usage='%prog [options]')
    parser.add_option('--no-ipython', dest='no_ipython', action='store_true',
                      help='Do not launch ipython, even if present.')
    parser.add_option('--instance', '-I', dest='instance',
                      help='Use the path provided as TextPress instance.')
    options, args = parser.parse_args()
    if args:
        parser.error('incorrect number of arguments')
    instance = options.instance or find_instance()
    if instance is None:
        parser.error('instance not found.  Specify path to instance')

    make_shell(lambda: init_func(instance), banner='TextPress Shell [%s]' %
               abspath(instance))(ipython=not options.no_ipython)


if __name__ == '__main__':
    main()
